# Generated by Django 3.0.8 on 2020-07-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity_Scheduler', '0004_auto_20200730_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Class',
        ),
        migrations.AddField(
            model_name='class',
            name='courses',
            field=models.ManyToManyField(to='Activity_Scheduler.Course'),
        ),
    ]
