# Generated by Django 3.0.8 on 2020-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity_Scheduler', '0005_auto_20200730_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='courses',
            field=models.ManyToManyField(default=None, to='Activity_Scheduler.Course'),
        ),
    ]
