# Generated by Django 3.0.8 on 2020-08-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sections', models.SmallIntegerField()),
                ('dwk', models.SmallIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('crtHours', models.SmallIntegerField()),
                ('count', models.SmallIntegerField(default=0)),
                ('Class', models.ManyToManyField(default=None, to='Activity_Scheduler.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=130)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Activity_Scheduler.Class')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=50, null=True)),
                ('room', models.SmallIntegerField(null=True)),
                ('section', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
                ('period', models.SmallIntegerField()),
                ('Timetable', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Activity_Scheduler.Timetable')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Activity_Scheduler.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity_Scheduler.Teacher'),
        ),
    ]
