# Generated by Django 3.0.8 on 2020-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='period',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='section',
            field=models.SmallIntegerField(null=True),
        ),
    ]
